apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    #name: guestbook
    namespace: guestbook
    server: https://192.168.59.102:8443
  source:
    path: guestbook
    repoURL: https://github.com/sspk/argocd-example-apps.git
    targetRevision: master
  project: default
